[project]
name = "uv-p1"
version = "0.1.0"
description = "uv package 1"
readme = "README.md"
authors = [
    { name = "Ondrej Profant", email = "ondrej.profant@datamole.ai" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]

[project.scripts]
uv-p1 = "uv_p1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "ruff>=0.11.13",
    "twine>=6.1.0",
]
