name: Dynamic Pipeline

on: [push]

env:
  CHANGELOG_FILE: CHANGELOG.md
  FULL_CHANGELOG_FILE: FULL_CHANGELOG.md

jobs:
  packages_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install os dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd packages/uv-p1
          uv sync
      - name: Run checks
        run: |
          cd packages/uv-p1
          uv run --group dev ruff --config ../../ruff.toml check .
          uv run --group dev ruff --config ../../ruff.toml format . --check
          uv run --group dev pytest tests/

  generate_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Install os dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd packages/uv-p1
          uv sync
      - name: Generate packages
        run: |
          cd packages/uv-p1
          uv build
          uv run --group dev twine check dist/*
          # twine upload dist/* --non-interactive
